[package]
name = "runtime-rebalancer"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
runtime-core = { path = "../runtime-core" }
runtime-execution-planner = { path = "../runtime-execution-planner" }
runtime-telemetry = { path = "../runtime-telemetry" }

[lib]
path = "src/lib.rs"
