[package]
name = "runtime-cost-model"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
runtime-core = { path = "../runtime-core" }
runtime-machine = { path = "../runtime-machine" }
runtime-selector = { path = "../runtime-selector" }
runtime-telemetry = { path = "../runtime-telemetry" }

[lib]
path = "src/lib.rs"
